{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sreagent.fullname" . }}-mysql
  labels:
    {{- include "sreagent.labels" . | nindent 4 }}
    component: mysql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "sreagent.selectorLabels" . | nindent 4 }}
    component: mysql
{{- end }}

